<?php

namespace Database\Seeders;

use App\Models\CRM\BaremeTravauxTag;
use Illuminate\Database\Seeder;

class BaremeTravauxTagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-164 BAR-TH-164',
            'bareme_description' => "Rénovation globale d'une maison individuelle" ,
            'travaux' => "Rénovation globale d'une maison individuelle",
            'tag' => 'TH164',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>0,
            'grand_precaire_montant_maprime_fioul' => 0,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 0,
            'precaire_montant_maprime_fioul' => 0,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 7000,
            'intermediaire_montant_maprime_fioul' => 7000,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 3500,
            'classique_montant_maprime_fioul' => 3500,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
        
        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-113',
            'bareme_description' => 'Chaudière biomasse individuelle',
            'travaux' => 'Chaudières à granulés',
            'tag' => 'CAG',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' => 11000,
            'grand_precaire_montant_maprime_fioul' => 11000,
            'grand_precaire_montant_cee_no_fioul' => 4000,
            'grand_precaire_montant_cee_fioul' => 5000,
            'precaire_montant_maprime_no_fioul' => 9000,
            'precaire_montant_maprime_fioul' => 8500,
            'precaire_montant_cee_no_fioul' => 4000,
            'precaire_montant_cee_fioul' => 5000,
            'intermediaire_montant_maprime_no_fioul' => 5000,
            'intermediaire_montant_maprime_fioul' => 5000,
            'intermediaire_montant_cee_no_fioul' => 2500,
            'intermediaire_montant_cee_fioul' => 4000,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 2500,
            'classique_montant_cee_fioul' => 4000,
        ]);

        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-104',
            'bareme_description' => 'Pompe à chaleur de type air/eau',
            'travaux' => 'Pompes à chaleur air/eau',
            'tag' => 'PAC R/O',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>5000,
            'grand_precaire_montant_maprime_fioul' => 5000,
            'grand_precaire_montant_cee_no_fioul' => 4000,
            'grand_precaire_montant_cee_fioul' => 5000,
            'precaire_montant_maprime_no_fioul' => 4000,
            'precaire_montant_maprime_fioul' => 4000,
            'precaire_montant_cee_no_fioul' => 4000,
            'precaire_montant_cee_fioul' => 5000,
            'intermediaire_montant_maprime_no_fioul' => 3000,
            'intermediaire_montant_maprime_fioul' => 3000,
            'intermediaire_montant_cee_no_fioul' => 2500,
            'intermediaire_montant_cee_fioul' => 4000,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 2500,
            'classique_montant_cee_fioul' => 4000,

        ]);

        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-143',
            'bareme_description' => 'Système solaire combiné',
            'travaux' => 'Système Solaire Combiné',
            'tag' => 'SSC',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>11000,
            'grand_precaire_montant_maprime_fioul' => 11000,
            'grand_precaire_montant_cee_no_fioul' => 4000,
            'grand_precaire_montant_cee_fioul' => 5000,
            'precaire_montant_maprime_no_fioul' => 9000,
            'precaire_montant_maprime_fioul' => 9000,
            'precaire_montant_cee_no_fioul' => 4000,
            'precaire_montant_cee_fioul' => 5000,
            'intermediaire_montant_maprime_no_fioul' => 5000,
            'intermediaire_montant_maprime_fioul' => 5000,
            'intermediaire_montant_cee_no_fioul' => 2500,
            'intermediaire_montant_cee_fioul' => 4000,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 2500,
            'classique_montant_cee_fioul' => 4000,

        ]);
        
        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-148',
            'bareme_description' => 'Chauffe-eau thermodynamique à accumulation',
            'travaux' => 'Système Solaire Combiné',
            'tag' => 'ECS TH',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>12000,
            'grand_precaire_montant_maprime_fioul' => 12000,
            'grand_precaire_montant_cee_no_fioul' => 81,
            'grand_precaire_montant_cee_fioul' => 81,
            'precaire_montant_maprime_no_fioul' => 800,
            'precaire_montant_maprime_fioul' => 800,
            'precaire_montant_cee_no_fioul' => 81,
            'precaire_montant_cee_fioul' => 81,
            'intermediaire_montant_maprime_no_fioul' => 400,
            'intermediaire_montant_maprime_fioul' => 400,
            'intermediaire_montant_cee_no_fioul' => 81,
            'intermediaire_montant_cee_fioul' => 81,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 81,
            'classique_montant_cee_fioul' => 81,
        ]);
        
        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-101',
            'bareme_description' => 'Chauffe-eau solaire individuel',
            'travaux' => 'Chauffe-eau solaire',
            'tag' => 'CESI',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>4000,
            'grand_precaire_montant_maprime_fioul' => 4000,
            'grand_precaire_montant_cee_no_fioul' => 100,
            'grand_precaire_montant_cee_fioul' => 100,
            'precaire_montant_maprime_no_fioul' => 3000,
            'precaire_montant_maprime_fioul' => 3000,
            'precaire_montant_cee_no_fioul' => 100,
            'precaire_montant_cee_fioul' => 100,
            'intermediaire_montant_maprime_no_fioul' => 2000,
            'intermediaire_montant_maprime_fioul' => 2000,
            'intermediaire_montant_cee_no_fioul' => 100,
            'intermediaire_montant_cee_fioul' => 100,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 100,
            'classique_montant_cee_fioul' => 100,

        ]);

        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-129',
            'bareme_description' => 'Pompe à chaleur de type air/air',
            'travaux' => 'Pompes à chaleur air/air',
            'tag' => 'PAC R/R',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>0,
            'grand_precaire_montant_maprime_fioul' => 0,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 0,
            'precaire_montant_maprime_fioul' => 0,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 0,
            'intermediaire_montant_maprime_fioul' => 0,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
        
        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-125',
            'bareme_description' => "Système de ventilation double flux autoréglable ou modulé" ,
            'travaux' => "VMC Double Flux",
            'tag' => 'VMC DBF',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>4000,
            'grand_precaire_montant_maprime_fioul' => 4000,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 3000,
            'precaire_montant_maprime_fioul' => 3000,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 2000,
            'intermediaire_montant_maprime_fioul' => 2000,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,

        ]);

        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-127',
            'bareme_description' => "Ventilation mécanique simple flux hygroréglable" ,
            'travaux' => "VMC SIMPLE Flux",
            'tag' => 'VMC SF',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>0,
            'grand_precaire_montant_maprime_fioul' => 0,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 0,
            'precaire_montant_maprime_fioul' => 0,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 0,
            'intermediaire_montant_maprime_fioul' => 0,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
        
        BaremeTravauxTag::create([
            'bareme' => 'BAR-TH-112',
            'bareme_description' => "Appareil indépendant de chauffage au bois" ,
            'travaux' => "Poêles à granulés",
            'tag' => 'POELE',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>3000,
            'grand_precaire_montant_maprime_fioul' => 3000,
            'grand_precaire_montant_cee_no_fioul' => 110,
            'grand_precaire_montant_cee_fioul' => 110,
            'precaire_montant_maprime_no_fioul' => 2500,
            'precaire_montant_maprime_fioul' => 2500,
            'precaire_montant_cee_no_fioul' => 110,
            'precaire_montant_cee_fioul' => 110,
            'intermediaire_montant_maprime_no_fioul' => 1500,
            'intermediaire_montant_maprime_fioul' => 1500,
            'intermediaire_montant_cee_no_fioul' => 110,
            'intermediaire_montant_cee_fioul' => 110,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 110,
            'classique_montant_cee_fioul' => 0,
        ]);
        BaremeTravauxTag::create([
            'bareme' => 'BAR-EN-101',
            'bareme_description' => "Isolation de combles ou de toiture." ,
            'travaux' => "Isolation de combles ou de toiture",
            'tag' => 'ITI_101',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>0,
            'grand_precaire_montant_maprime_fioul' => 0,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 0,
            'precaire_montant_maprime_fioul' => 0,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 0,
            'intermediaire_montant_maprime_fioul' => 0,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
        BaremeTravauxTag::create([
            'bareme' => 'BAR-EN-102',
            'bareme_description' => "Isolation des murs" ,
            'travaux' => "Isolation des murs par l'interieur",
            'tag' => 'ITI_102',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>25,
            'grand_precaire_montant_maprime_fioul' => 25,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 20,
            'precaire_montant_maprime_fioul' => 20,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 15,
            'intermediaire_montant_maprime_fioul' => 15,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 7,
            'classique_montant_maprime_fioul' => 7,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
        BaremeTravauxTag::create([
            'bareme' => 'BAR-EN-102',
            'bareme_description' => "Isolation des murs" ,
            'travaux' => "Isolation des murs par l'extérieur",
            'tag' => 'ITE_102',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>75,
            'grand_precaire_montant_maprime_fioul' => 75,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 60,
            'precaire_montant_maprime_fioul' => 60,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 40,
            'intermediaire_montant_maprime_fioul' => 40,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 15,
            'classique_montant_maprime_fioul' => 15,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);

        BaremeTravauxTag::create([
            'bareme' => 'BAR-EN-103',
            'bareme_description' => "Isolation d’un plancher" ,
            'travaux' => "Isolation d’un plancher",
            'tag' => 'ITE_103',
            'rank' => 1,
            'grand_precaire_montant_maprime_no_fioul' =>0,
            'grand_precaire_montant_maprime_fioul' => 0,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 0,
            'precaire_montant_maprime_fioul' => 0,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 0,
            'intermediaire_montant_maprime_fioul' => 0,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
        BaremeTravauxTag::create([
            'bareme' => 'NO CEE',
            'bareme_description' => "" ,
            'travaux' => "CUVE",
            'tag' => 'CUVE',
            'rank' => 2,
            'grand_precaire_montant_maprime_no_fioul' =>1200,
            'grand_precaire_montant_maprime_fioul' => 1200,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 800,
            'precaire_montant_maprime_fioul' =>800,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 400,
            'intermediaire_montant_maprime_fioul' => 400,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
        
        BaremeTravauxTag::create([
            'bareme' => 'NO CEE',
            'bareme_description' => "" ,
            'travaux' => 'Bonus "Sortie de passoire énergétique"',
            'tag' => 'B_SPEC',
            'rank' => 2,
            'grand_precaire_montant_maprime_no_fioul' =>1500,
            'grand_precaire_montant_maprime_fioul' => 1500,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 1500,
            'precaire_montant_maprime_fioul' =>8000,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 1000,
            'intermediaire_montant_maprime_fioul' => 1000,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 500,
            'classique_montant_maprime_fioul' => 500,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
        BaremeTravauxTag::create([
            'bareme' => 'NO CEE',
            'bareme_description' => "" ,
            'travaux' => 'Bonus "Bâtiment basse consommation"',
            'tag' => 'B_BBC',
            'rank' => 2,
            'grand_precaire_montant_maprime_no_fioul' =>1500,
            'grand_precaire_montant_maprime_fioul' => 1500,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 1500,
            'precaire_montant_maprime_fioul' =>8000,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 1000,
            'intermediaire_montant_maprime_fioul' => 1000,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 500,
            'classique_montant_maprime_fioul' => 500,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);

        BaremeTravauxTag::create([
            'bareme' => 'NO CEE',
            'bareme_description' => "" ,
            'travaux' => 'AUDIT',
            'tag' => 'AUDIT',
            'rank' => 2,
            'grand_precaire_montant_maprime_no_fioul' =>500,
            'grand_precaire_montant_maprime_fioul' => 500,
            'grand_precaire_montant_cee_no_fioul' => 0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 400,
            'precaire_montant_maprime_fioul' =>400,
            'precaire_montant_cee_no_fioul' => 0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 300,
            'intermediaire_montant_maprime_fioul' => 300,
            'intermediaire_montant_cee_no_fioul' => 0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
        
        BaremeTravauxTag::create([
            'bareme' => 'NO CEE',
            'bareme_description' => "" ,
            'travaux' => 'Creation conduit double paroi',
            'tag' => 'DPI',
            'rank' => 2,
            'grand_precaire_montant_maprime_no_fioul' =>0,
            'grand_precaire_montant_maprime_fioul' => 0,
            'grand_precaire_montant_cee_no_fioul' =>0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 0,
            'precaire_montant_maprime_fioul' =>0,
            'precaire_montant_cee_no_fioul' =>0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 0,
            'intermediaire_montant_maprime_fioul' =>0,
            'intermediaire_montant_cee_no_fioul' =>0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,


        ]);
        
        BaremeTravauxTag::create([
            'bareme' => 'NO CEE',
            'bareme_description' => "" ,
            'travaux' => "SILO MIDI",
            'tag' => 'SILO MDI',
            'rank' => 2,
            'grand_precaire_montant_maprime_no_fioul' =>0,
            'grand_precaire_montant_maprime_fioul' => 0,
            'grand_precaire_montant_cee_no_fioul' =>0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 0,
            'precaire_montant_maprime_fioul' =>0,
            'precaire_montant_cee_no_fioul' =>0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 0,
            'intermediaire_montant_maprime_fioul' =>0,
            'intermediaire_montant_cee_no_fioul' =>0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);

        BaremeTravauxTag::create([
            'bareme' => 'NO CEE',
            'bareme_description' => "" ,
            'travaux' => "Creation point d'eau",
            'tag' => 'PO',
            'rank' => 2,
            'grand_precaire_montant_maprime_no_fioul' =>0,
            'grand_precaire_montant_maprime_fioul' => 0,
            'grand_precaire_montant_cee_no_fioul' =>0,
            'grand_precaire_montant_cee_fioul' => 0,
            'precaire_montant_maprime_no_fioul' => 0,
            'precaire_montant_maprime_fioul' =>0,
            'precaire_montant_cee_no_fioul' =>0,
            'precaire_montant_cee_fioul' => 0,
            'intermediaire_montant_maprime_no_fioul' => 0,
            'intermediaire_montant_maprime_fioul' =>0,
            'intermediaire_montant_cee_no_fioul' =>0,
            'intermediaire_montant_cee_fioul' => 0,
            'classique_montant_maprime_no_fioul' => 0,
            'classique_montant_maprime_fioul' => 0,
            'classique_montant_cee_no_fioul' => 0,
            'classique_montant_cee_fioul' => 0,
        ]);
    }
}
