<?php

namespace Database\Seeders;

use App\Models\CRM\DocumentField;
use Illuminate\Database\Seeder;

class DocumentFieldSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $document_fields = [
            ['document_id' => 1,  'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 1,  'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 1,  'field_title' => 'NUMERO DOSSIER',                 'field_name' => 'NUMERO_DOSSIER',              'field_type' => 'text',     'column_value' => 'dossier_number'],
            ['document_id' => 1,  'field_title' => 'Email',                          'field_name' => 'Email',                       'field_type' => 'text',     'column_value' => 'Email'],
            ['document_id' => 1,  'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 2,  'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 2,  'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 2,  'field_title' => 'NUMERO DOSSIER',                 'field_name' => 'NUMERO_DOSSIER',              'field_type' => 'text',     'column_value' => 'dossier_number'],
            ['document_id' => 2,  'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 4, 'field_title' => 'NOM CLIENT',                      'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 4, 'field_title' => 'Fait à',                          'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 4, 'field_title' => 'Le',                              'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'date_intervention'],

            ['document_id' => 5, 'field_title' => 'Bénéficiaire',                    'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 5, 'field_title' => 'Adresse des travaux',             'field_name' => 'Adresse_des_travaux',         'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 5, 'field_title' => 'Parcelle cadastrale',             'field_name' => 'Parcelle_cadastrale',         'field_type' => 'text',     'column_value' => 'Parcelle_cadastrale'],
            ['document_id' => 5, 'field_title' => 'Tél',                             'field_name' => 'Tél',                         'field_type' => 'text',     'column_value' => 'phone'],
            ['document_id' => 5, 'field_title' => 'E-mail',                          'field_name' => 'Email',                       'field_type' => 'text',     'column_value' => 'Email'],
            ['document_id' => 5, 'field_title' => 'Zone',                            'field_name' => 'Zone',                        'field_type' => 'text',     'column_value' => 'Zone'],
            ['document_id' => 5, 'field_title' => 'Surface chauffée',                'field_name' => 'Surface_chauffée',            'field_type' => 'number',   'column_value' => 'Surface_à_chauffer'],
            ['document_id' => 5, 'field_title' => 'Hauteur sous plafond',            'field_name' => 'Hauteur_sous_plafond',        'field_type' => 'number',   'column_value' => null],
            ['document_id' => 5, 'field_title' => 'Altitude',                        'field_name' => 'Altitude',                    'field_type' => 'number',   'column_value' => null], 
            ['document_id' => 5, 'field_title' => 'Emetteur de chauffage existant',  'field_name' => 'Emetteur_de_chauffage',       'field_type' => 'text',     'column_value' => null],
            ['document_id' => 5, 'field_title' => 'Température d’eau',               'field_name' => 'Température',                 'field_type' => 'text',     'column_value' => null], 
            ['document_id' => 5, 'field_title' => 'Type de produit',                 'field_name' => 'Type_de_produit',             'field_type' => 'text',     'column_value' => null],
            ['document_id' => 5, 'field_title' => 'Marque',                          'field_name' => 'Marque',                      'field_type' => 'select',   'column_value' => 'marque_dropdown'],
            ['document_id' => 5, 'field_title' => 'Référence',                       'field_name' => 'Référence',                   'field_type' => 'select',   'column_value' => 'product_refrence'],
            ['document_id' => 5, 'field_title' => 'Température ambiante souhaitée',  'field_name' => 'Température_ambiante',        'field_type' => 'text',     'column_value' => null],
            ['document_id' => 5, 'field_title' => 'Température extérieure de base',  'field_name' => 'Température_extérieure',      'field_type' => 'text',     'column_value' => null],
            ['document_id' => 5, 'field_title' => 'Coefficient de construction',     'field_name' => 'Coefficient_de_construction', 'field_type' => 'number',   'column_value' => null],
            ['document_id' => 5, 'field_title' => 'déperditions',                   'field_name' => 'déperditions',                 'field_type' => 'number',   'column_value' => null],
            ['document_id' => 5, 'field_title' => 'Puissance définie du à la température de base', 'field_name' => 'Puissance_définie_du_à_la_température', 'field_type' => 'number',   'column_value' => null],
            ['document_id' => 5, 'field_title' => 'Taux de couverture',             'field_name' => 'Taux_de_couverture',           'field_type' => 'number',   'column_value' => null],
            ['document_id' => 5, 'field_title' => 'Fait à',                          'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 5, 'field_title' => 'Le',                              'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'date_intervention'],


            ['document_id' => 6, 'field_title' => 'Déclarant 1 Nom',                 'field_name' => 'Déclarant_1_Nom',             'field_type' => 'text',     'column_value' => 'Nom'],
            ['document_id' => 6, 'field_title' => 'Déclarant 2 Nom',                 'field_name' => 'Déclarant_2_Nom',             'field_type' => 'text',     'column_value' => 'Déclarant_2_Nom'], 
            ['document_id' => 6, 'field_title' => 'Déclarant 1 Nom de naissance',    'field_name' => 'Déclarant_1_Nom_de_naissance','field_type' => 'text',     'column_value' => 'Nom'],
            ['document_id' => 6, 'field_title' => 'Déclarant 2 Nom de naissance',    'field_name' => 'Déclarant_2_Nom_de_naissance','field_type' => 'text',     'column_value' => 'Déclarant_2_Nom'], 
            ['document_id' => 6, 'field_title' => 'Déclarant 1 Prénom',              'field_name' => 'Déclarant_1_Prénom',          'field_type' => 'text',     'column_value' => 'Prenom'],
            ['document_id' => 6, 'field_title' => 'Déclarant 2 Prénom',              'field_name' => 'Déclarant_2_Prénom',          'field_type' => 'text',     'column_value' => 'Déclarant_2_Prenom'], 
            ['document_id' => 6, 'field_title' => 'Déclarant 1 Date de naissance',   'field_name' => 'Déclarant_1_Date_de_naissance','field_type' => 'date',    'column_value' => null],
            ['document_id' => 6, 'field_title' => 'Déclarant 2 Date de naissance',   'field_name' => 'Déclarant_2_Date_de_naissance','field_type' => 'date',    'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Adresse déclarée au 1er janvier 2020",   'field_name' => 'Adresse_déclarée', 'field_type' => 'textarea',    'column_value' => 'full_address'], 
            ['document_id' => 6, 'field_title' => "Date de mise en recouvrement de l'avis d'impôt",   'field_name' => 'Date_de_mise_en_recouvrement', 'field_type' => 'date',    'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Date d'établissement",            'field_name' => "Date_établissement",          'field_type' => 'date',     'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Nombre de part(s)",               'field_name' => "Nombre_de_part",              'field_type' => 'number',   'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Situation de famille",            'field_name' => "Situation_de_famille",        'field_type' => 'text',     'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Nombre de personne(s) à charge",  'field_name' => "Nombre_de_personne",          'field_type' => 'number',   'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Revenu brut global",              'field_name' => "Revenu_brut_global",          'field_type' => 'number',   'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Revenu imposable",                'field_name' => "Revenu_imposable",            'field_type' => 'number',   'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Impôt sur le revenu net avant corrections", 'field_name' => "Impôt_sur_le_revenu_net_avant_corrections", 'field_type' => 'text',   'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Montant de l'impôt",             'field_name' => "Montant_de_impôt",             'field_type' => 'text',     'column_value' => null], 
            ['document_id' => 6, 'field_title' => "Revenu fiscal de référence",     'field_name' => "Revenu_fiscal_de_référence",   'field_type' => 'number',   'column_value' => 'Revenue_Fiscale_de_Référence'], 
            ['document_id' => 6, 'field_title' => "Numéro fiscal",                  'field_name' => "Numéro_fiscal",                'field_type' => 'text',     'column_value' => 'Numéro_fiscal'], 
            ['document_id' => 6, 'field_title' => "Référence avis",                 'field_name' => "Référence_avis",               'field_type' => 'text',     'column_value' => 'Référence_avis'], 

            ['document_id' => 7,  'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 7,  'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 7,  'field_title' => 'Mode de chauffage',              'field_name' => 'Mode_de_chauffage',           'field_type' => 'select',   'column_value' => 'Mode_de_chauffage__static'],
            ['document_id' => 7,  'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 8,  'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 8,  'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 8,  'field_title' => 'Mode de chauffage',              'field_name' => 'Mode_de_chauffage',           'field_type' => 'select',   'column_value' => 'Mode_de_chauffage__static1'],
            ['document_id' => 8,  'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 9,  'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 9,  'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 9,  'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 9,  'field_title' => 'Le',                             'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'date_intervention'],

            ['document_id' => 10, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 10, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 10, 'field_title' => 'Référence de l’avis d’impots',   'field_name' => 'Référence_de',                'field_type' => 'text',     'column_value' => null],
            ['document_id' => 10, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 11, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 11, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 11, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 12, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 12, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 12, 'field_title' => 'Le',                             'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'date_intervention'],

            ['document_id' => 13, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 13, 'field_title' => 'Le',                             'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'date_intervention'],

            ['document_id' => 14, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 14, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 14, 'field_title' => 'TRAVAUX',                        'field_name' => 'TRAVAUX',                     'field_type' => 'select',   'column_value' => 'travaux'],
            ['document_id' => 14, 'field_title' => 'MONTANT Subvention Accordé',     'field_name' => 'MONTANT_Subvention_Accordé',  'field_type' => 'text',     'column_value' => null],
            ['document_id' => 14, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 15, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 15, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 15, 'field_title' => 'Code Postal',                    'field_name' => 'Code_Postal',                 'field_type' => 'text',     'column_value' => 'Code_Postal'],
            ['document_id' => 15, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 15, 'field_title' => 'DATE DU JOUR',                   'field_name' => 'DATE_DU_JOUR',                'field_type' => 'date',     'column_value' => 'today'],

            ['document_id' => 16, 'field_title' => "MAÎTRE D'ŒUVRE: Société",                       'field_name' => 'MAÎTRE_Société',                           'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "MAÎTRE D'ŒUVRE: Nom du correspondant",          'field_name' => 'MAÎTRE_Nom_du_correspondant',              'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "MAÎTRE D'ŒUVRE: Adresse",                       'field_name' => 'MAÎTRE_Adresse',                           'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 16, 'field_title' => "MAÎTRE D'ŒUVRE: Code postal",                   'field_name' => 'MAÎTRE_Code_postal',                       'field_type' => 'text',     'column_value' => 'Code_Postal'],
            ['document_id' => 16, 'field_title' => "MAÎTRE D'ŒUVRE: Ville",                         'field_name' => 'MAÎTRE_Ville',                             'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 16, 'field_title' => "MAÎTRE D'ŒUVRE: Téléphone",                     'field_name' => 'MAÎTRE_Téléphone',                         'field_type' => 'text',     'column_value' => 'phone'],
            ['document_id' => 16, 'field_title' => "MAÎTRE D'ŒUVRE: Portable",                      'field_name' => 'MAÎTRE_Portable',                          'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "MAÎTRE D'ŒUVRE: E-mail",                        'field_name' => 'MAÎTRE_Email',                             'field_type' => 'text',     'column_value' => 'Email'],
            ['document_id' => 16, 'field_title' => "MAÎTRE D'ŒUVRE: L’installateur atteste....",    'field_name' => 'MAÎTRE_Linstallateur_atteste',             'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "MISE EN PLACE PAR: Société",                    'field_name' => 'mise_en_Société',                          'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "MISE EN PLACE PAR: Nom du correspondant",       'field_name' => 'mise_en_Nom_du_correspondant',             'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "MISE EN PLACE PAR: Adresse",                    'field_name' => 'mise_en_Adresse',                          'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 16, 'field_title' => "MISE EN PLACE PAR: Code postal",                'field_name' => 'mise_en_Code_postal',                      'field_type' => 'text',     'column_value' => 'Code_Postal'],
            ['document_id' => 16, 'field_title' => "MISE EN PLACE PAR: Ville",                      'field_name' => 'mise_en_Ville',                            'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 16, 'field_title' => "MISE EN PLACE PAR: Téléphone",                  'field_name' => 'mise_en_Téléphone',                        'field_type' => 'text',     'column_value' => 'phone'],
            ['document_id' => 16, 'field_title' => "MISE EN PLACE PAR: Portable",                   'field_name' => 'mise_en_Portable',                         'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "MISE EN PLACE PAR: L’installateur atteste....", 'field_name' => 'mise_en_Linstallateur_atteste',            'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "BÉNÉFICIAIRE: Nom",                             'field_name' => 'BÉNÉFICIAIRE_Nom',                         'field_type' => 'text',     'column_value' => 'Nom'],
            ['document_id' => 16, 'field_title' => "BÉNÉFICIAIRE: Prénom",                          'field_name' => 'BÉNÉFICIAIRE_Prénom',                      'field_type' => 'text',     'column_value' => 'Prenom'],
            ['document_id' => 16, 'field_title' => "BÉNÉFICIAIRE: Adresse",                         'field_name' => 'BÉNÉFICIAIRE_Adresse',                     'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 16, 'field_title' => "BÉNÉFICIAIRE: Code postal",                     'field_name' => 'BÉNÉFICIAIRE_Code_postal',                 'field_type' => 'text',     'column_value' => 'Code_Postal'],
            ['document_id' => 16, 'field_title' => "BÉNÉFICIAIRE: Ville",                           'field_name' => 'BÉNÉFICIAIRE_Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 16, 'field_title' => "BÉNÉFICIAIRE: Téléphone",                       'field_name' => 'BÉNÉFICIAIRE_Téléphone',                   'field_type' => 'text',     'column_value' => 'phone'],
            ['document_id' => 16, 'field_title' => "BÉNÉFICIAIRE: Portable",                        'field_name' => 'BÉNÉFICIAIRE_Portable',                    'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "BÉNÉFICIAIRE: E-mail",                          'field_name' => 'BÉNÉFICIAIRE_Email',                       'field_type' => 'text',     'column_value' => 'Email'],
            ['document_id' => 16, 'field_title' => "MATÉRIEL: Matériel existant",                   'field_name' => 'Matériel_existant',                        'field_type' => 'checkbox',   'column_value' => 'Matériel_existant'],
            ['document_id' => 16, 'field_title' => "MATÉRIEL: Matériel posé",                       'field_name' => 'Matériel_posé',                            'field_type' => 'checkbox',   'column_value' => 'Matériel_posé'],
            ['document_id' => 16, 'field_title' => "MATÉRIEL: Type",                                'field_name' => 'Matériel_type',                            'field_type' => 'text',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "MATÉRIEL: Date de première mise en route",      'field_name' => 'Matériel_Date_de_première_mise_en_route',  'field_type' => 'date',     'column_value' => null],
            ['document_id' => 16, 'field_title' => "MATÉRIEL: Problèmes éventuels",                 'field_name' => 'Matériel_Problèmes_éventuels',             'field_type' => 'checkbox',   'column_value' => 'Matériel_Problèmes_éventuels'],
            ['document_id' => 16, 'field_title' => "MATÉRIEL: Le bénéficiaire atteste...",          'field_name' => 'Matériel_Le_bénéficiaire_atteste',         'field_type' => 'checkbox',   'column_value' => 'Matériel_Le_bénéficiaire_atteste'],
            
            ['document_id' => 17, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 17, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 17, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 17, 'field_title' => 'DATE DU JOUR',                   'field_name' => 'DATE_DU_JOUR',                'field_type' => 'date',     'column_value' => 'today'],

            ['document_id' => 18, 'field_title' => 'DATE DU JOUR',                   'field_name' => 'DATE_DU_JOUR',                'field_type' => 'date',     'column_value' => 'today'],
            ['document_id' => 18, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 18, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 18, 'field_title' => 'TRAVAUX',                        'field_name' => 'TRAVAUX',                     'field_type' => 'select',   'column_value' => 'travaux'],
            ['document_id' => 18, 'field_title' => 'PRODUIT',                        'field_name' => 'PRODUIT',                     'field_type' => 'text',     'column_value' => null],
            ['document_id' => 18, 'field_title' => 'NUMÉRO DE DEVIS',                'field_name' => 'NUMÉRO_DE_DEVIS',             'field_type' => 'number',   'column_value' => null],
            ['document_id' => 18, 'field_title' => 'Montant attestation RAC',        'field_name' => 'Montant_attestation_RAC',     'field_type' => 'text',     'column_value' => null],

            ['document_id' => 19, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 19, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 19, 'field_title' => 'Description',                    'field_name' => 'Description',                 'field_type' => 'textarea', 'column_value' => null],
            ['document_id' => 19, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 20, 'field_title' => 'Nom',                            'field_name' => 'Nom',                         'field_type' => 'text',     'column_value' => 'Nom'],
            ['document_id' => 20, 'field_title' => "Prénom",                         'field_name' => 'Prénom',                      'field_type' => 'text',     'column_value' => 'Prenom'],
            ['document_id' => 20, 'field_title' => 'Adresse',                        'field_name' => 'Adresse',                     'field_type' => 'textarea', 'column_value' => 'Adresse'],
            ['document_id' => 20, 'field_title' => 'Code postal',                    'field_name' => 'Code_postal',                 'field_type' => 'number',   'column_value' => 'Code_Postal'],
            ['document_id' => 20, 'field_title' => 'Commune',                        'field_name' => 'Commune',                     'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 20, 'field_title' => 'NATURE DES LOCAUX',              'field_name' => 'NATURE_DES_LOCAUX',           'field_type' => 'checkbox', 'column_value' => 'NATURE_DES_LOCAUX'],
            ['document_id' => 20, 'field_title' => 'Les travaux sont réalisés dans', 'field_name' => 'Les_travaux_sont_réalisés_dans','field_type' => 'checkbox', 'column_value' => 'Les_travaux_sont_réalisés_dans'],
            ['document_id' => 20, 'field_title' => 'Adresse2',                       'field_name' => 'Adresse2',                    'field_type' => 'textarea', 'column_value' => 'Adresse'],
            ['document_id' => 20, 'field_title' => 'Code postal',                    'field_name' => 'Code_postal2',                'field_type' => 'number',   'column_value' => 'Code_Postal'],
            ['document_id' => 20, 'field_title' => 'Commune',                        'field_name' => 'Commune2',                    'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 20, 'field_title' => 'dont je suis',                  'field_name' => 'dont_je_suis',                 'field_type' => 'checkbox', 'column_value' => 'dont_je_suis'],
            ['document_id' => 20, 'field_title' => 'NATURE DES TRAVAUX',            'field_name' => 'NATURE_DES_TRAVAUX',           'field_type' => 'checkbox', 'column_value' => 'NATURE_DES_TRAVAUX'],
            ['document_id' => 20, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 20, 'field_title' => 'Le',                             'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'today'],
            
            ['document_id' => 21, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 21, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],

            ['document_id' => 22, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 22, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 22, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 22, 'field_title' => 'DATE DU JOUR',                   'field_name' => 'DATE_DU_JOUR',                'field_type' => 'date',     'column_value' => 'today'],

            ['document_id' => 26, 'field_title' => 'prime d’un montant',             'field_name' => 'prime_montant',               'field_type' => 'number',   'column_value' => null],
            ['document_id' => 26, 'field_title' => 'Nature des travaux',             'field_name' => 'Nature_des_travaux',          'field_type' => 'select',   'column_value' => 'Nature_des_travaux'],
            ['document_id' => 26, 'field_title' => 'Nom',                            'field_name' => 'Nom',                         'field_type' => 'text',     'column_value' => 'Nom'],
            ['document_id' => 26, 'field_title' => "Prénom",                         'field_name' => 'Prénom',                      'field_type' => 'text',     'column_value' => 'Prenom'],
            ['document_id' => 26, 'field_title' => 'Adresse',                        'field_name' => 'Adresse',                     'field_type' => 'textarea', 'column_value' => 'Adresse'],
            ['document_id' => 26, 'field_title' => 'Téléphone',                      'field_name' => 'Téléphone',                   'field_type' => 'text',     'column_value' => 'phone'],
            ['document_id' => 26,  'field_title' => 'Adresse E-mail',                'field_name' => 'Email',                       'field_type' => 'text',     'column_value' => 'Email'],
            ['document_id' => 26, 'field_title' => 'Date de cette proposition',      'field_name' => 'Date_de_cette_proposition',   'field_type' => 'date',     'column_value' => null],

            ['document_id' => 27, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 27, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 28, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 28, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 29, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 29, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],

            ['document_id' => 32, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 32, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 33, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 33, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 34, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 34, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 35, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 35, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 36, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 36, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 37, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 37, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],

            ['document_id' => 41, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 41, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 41, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],
            
            ['document_id' => 44, 'field_title' => 'Nom et Prénom',                  'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 44, 'field_title' => 'MPR',                            'field_name' => 'MPR',                         'field_type' => 'number',   'column_value' => null],
            ['document_id' => 44, 'field_title' => 'FULL ADRESSE',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 44, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 44, 'field_title' => 'Le',                             'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'today'],

            ['document_id' => 45, 'field_title' => 'Nom',                            'field_name' => 'Nom',                         'field_type' => 'text',     'column_value' => 'Nom'],
            ['document_id' => 45, 'field_title' => 'Prénom',                         'field_name' => 'Prénom',                      'field_type' => 'text',     'column_value' => 'Prenom'],
            ['document_id' => 45, 'field_title' => 'Demeurant au',                   'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 45, 'field_title' => 'Pour rénover mon logement situé au','field_name' => 'FULL_ADRESSE2',            'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 45, 'field_title' => 'numéro de dossier',              'field_name' => 'NUMERO_DOSSIER',              'field_type' => 'text',     'column_value' => 'dossier_number'],
            ['document_id' => 45, 'field_title' => 'TRAVAUX 1',                      'field_name' => 'TRAVAUX1',                    'field_type' => 'select',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'TRAVAUX 2',                      'field_name' => 'TRAVAUX2',                    'field_type' => 'select',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'TRAVAUX 3',                      'field_name' => 'TRAVAUX3',                    'field_type' => 'select',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'TRAVAUX 4',                      'field_name' => 'TRAVAUX4',                    'field_type' => 'select',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'TRAVAUX 5',                      'field_name' => 'TRAVAUX5',                    'field_type' => 'select',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'Entreprise 1 Nom',               'field_name' => 'Entreprise_1_Nom',            'field_type' => 'text',     'column_value' => null],
            ['document_id' => 45, 'field_title' => 'Entreprise 1 N° de SIRET',       'field_name' => 'Entreprise_1_de_SIRET',       'field_type' => 'number',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'Entreprise 2 Nom',               'field_name' => 'Entreprise_2_Nom',            'field_type' => 'text',     'column_value' => null],
            ['document_id' => 45, 'field_title' => 'Entreprise 2 N° de SIRET',       'field_name' => 'Entreprise_2_de_SIRET',       'field_type' => 'number',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'Entreprise 3 Nom',               'field_name' => 'Entreprise_3_Nom',            'field_type' => 'text',     'column_value' => null],
            ['document_id' => 45, 'field_title' => 'Entreprise 3 N° de SIRET',       'field_name' => 'Entreprise_3_de_SIRET',       'field_type' => 'number',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'montant total TTC',              'field_name' => 'montant_total_TTC',           'field_type' => 'number',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'montant qui restera à ma charge','field_name' => 'montant_qui_restera_à_ma_charge','field_type' => 'number',   'column_value' => null],
            ['document_id' => 45, 'field_title' => 'Avoir mandaté un mandataire',    'field_name' => 'Avoir_mandaté_un_mandataire', 'field_type' => 'checkbox',   'column_value' => 'Avoir_mandaté_un_mandataire'],
            ['document_id' => 45, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 45, 'field_title' => 'Le',                             'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'today'],

            ['document_id' => 47, 'field_title' => 'NOM PRENOM PROPRIETAIRE 1',      'field_name' => 'NOM_PRENOM_PROPRIETAIRE_1',   'field_type' => 'text',     'column_value' => null],
            ['document_id' => 47, 'field_title' => 'DATE DE NAISSANCE PROPRIETAIRE 1','field_name' => 'DATE_DE_NAISSANCE_PROPRIETAIRE_1', 'field_type' => 'date','column_value' => null],
            ['document_id' => 47, 'field_title' => 'FULL ADRESSE PROPRIETAIRE 1','field_name' => 'FULL_ADRESSE_PROPRIETAIRE_1',     'field_type' => 'textarea',  'column_value' => null],
            ['document_id' => 47, 'field_title' => 'NOM PRENOM PROPRIETAIRE 2',      'field_name' => 'NOM_PRENOM_PROPRIETAIRE_2',   'field_type' => 'text',     'column_value' => null],
            ['document_id' => 47, 'field_title' => 'DATE DE NAISSANCE PROPRIETAIRE 2','field_name' => 'DATE_DE_NAISSANCE_PROPRIETAIRE_2', 'field_type' => 'date','column_value' => null],
            ['document_id' => 47, 'field_title' => 'FULL ADRESSE PROPRIETAIRE 2','field_name' => 'FULL_ADRESSE_PROPRIETAIRE_2',     'field_type' => 'textarea',  'column_value' => null],
            ['document_id' => 47, 'field_title' => 'NOM PRENOM PROPRIETAIRE 3',      'field_name' => 'NOM_PRENOM_PROPRIETAIRE_3',   'field_type' => 'text',     'column_value' => null],
            ['document_id' => 47, 'field_title' => 'DATE DE NAISSANCE PROPRIETAIRE 3','field_name' => 'DATE_DE_NAISSANCE_PROPRIETAIRE_3', 'field_type' => 'date','column_value' => null],
            ['document_id' => 47, 'field_title' => 'FULL ADRESSE PROPRIETAIRE 3','field_name' => 'FULL_ADRESSE_PROPRIETAIRE_3',     'field_type' => 'textarea',  'column_value' => null],
            ['document_id' => 47, 'field_title' => 'NOM PRENOM PROPRIETAIRE 4',      'field_name' => 'NOM_PRENOM_PROPRIETAIRE_4',   'field_type' => 'text',     'column_value' => null],
            ['document_id' => 47, 'field_title' => 'DATE DE NAISSANCE PROPRIETAIRE 4','field_name' => 'DATE_DE_NAISSANCE_PROPRIETAIRE_4', 'field_type' => 'date','column_value' => null],
            ['document_id' => 47, 'field_title' => 'FULL ADRESSE PROPRIETAIRE 4','field_name' => 'FULL_ADRESSE_PROPRIETAIRE_4',     'field_type' => 'textarea',  'column_value' => null],
            ['document_id' => 47, 'field_title' => 'NOM PRENOM PROPRIETAIRE 5',      'field_name' => 'NOM_PRENOM_PROPRIETAIRE_5',   'field_type' => 'text',     'column_value' => null],
            ['document_id' => 47, 'field_title' => 'DATE DE NAISSANCE PROPRIETAIRE 5','field_name' => 'DATE_DE_NAISSANCE_PROPRIETAIRE_5', 'field_type' => 'date','column_value' => null],
            ['document_id' => 47, 'field_title' => 'FULL ADRESSE PROPRIETAIRE 5','field_name' => 'FULL_ADRESSE_PROPRIETAIRE_5',     'field_type' => 'textarea',  'column_value' => null],
            ['document_id' => 47, 'field_title' => 'NOM PRENOM PROPRIETAIRE 6',      'field_name' => 'NOM_PRENOM_PROPRIETAIRE_6',   'field_type' => 'text',     'column_value' => null],
            ['document_id' => 47, 'field_title' => 'DATE DE NAISSANCE PROPRIETAIRE 6','field_name' => 'DATE_DE_NAISSANCE_PROPRIETAIRE_6', 'field_type' => 'date','column_value' => null],
            ['document_id' => 47, 'field_title' => 'FULL ADRESSE PROPRIETAIRE 6','field_name' => 'FULL_ADRESSE_PROPRIETAIRE_6',     'field_type' => 'textarea',  'column_value' => null],
            ['document_id' => 47,  'field_title' => 'FULL ADRESSE',                  'field_name' => 'FULL_ADRESSE',                'field_type' => 'textarea', 'column_value' => 'full_address'],
            ['document_id' => 47, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 47, 'field_title' => 'numéro de dossier',              'field_name' => 'NUMERO_DOSSIER',              'field_type' => 'text',     'column_value' => 'dossier_number'],
            ['document_id' => 47, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 47, 'field_title' => 'Le',                             'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'today'],
            

            ['document_id' => 48, 'field_title' => 'Type précarité',                 'field_name' => 'precariousness',              'field_type' => 'text',     'column_value' => 'precariousness'],
            ['document_id' => 48, 'field_title' => 'Téléphone',                      'field_name' => 'Téléphone',                   'field_type' => 'text',     'column_value' => 'phone'],
            ['document_id' => 48,  'field_title' => 'Courriel',                      'field_name' => 'Email',                       'field_type' => 'text',     'column_value' => 'Email'],
            ['document_id' => 48,  'field_title' => 'Revenu fiscal',                 'field_name' => 'Revenu_fiscal',               'field_type' => 'number',   'column_value' => 'Revenue_Fiscale_de_Référence'],
            ['document_id' => 48,  'field_title' => 'Nombre foyers',                 'field_name' => 'Nombre_foyers',               'field_type' => 'number',   'column_value' => 'Nombre_de_foyer'],
            ['document_id' => 48,  'field_title' => 'Nombre personnes',              'field_name' => 'Nombr_personnes',             'field_type' => 'number',   'column_value' => 'Nombre_de_personnes'],
            ['document_id' => 48,  'field_title' => 'Avis Fiscal 1',                 'field_name' => 'Avis_Fiscal_1',               'field_type' => 'text',     'column_value' => 'Avis_Fiscal_1'],
            ['document_id' => 48,  'field_title' => 'Avis Fiscal 2',                 'field_name' => 'Avis_Fiscal_2',               'field_type' => 'text',     'column_value' => 'Avis_Fiscal_2'],
            ['document_id' => 48, 'field_title' => 'Adresse',                        'field_name' => 'Adresse',                     'field_type' => 'textarea', 'column_value' => 'Adresse'],
            ['document_id' => 48, 'field_title' => 'Code postal / Ville',            'field_name' => 'Code_postal_Ville',           'field_type' => 'text', 'column_value' => 'Code_postal_Ville'],
            ['document_id' => 48, 'field_title' => 'Zone',                           'field_name' => 'Zone',                        'field_type' => 'text',     'column_value' => 'Zone'],
            ['document_id' => 48, 'field_title' => 'Mode de chauffage',              'field_name' => 'Mode_de_chauffage',           'field_type' => 'text',     'column_value' => 'Mode_de_chauffage'],
            ['document_id' => 48, 'field_title' => 'Total H.T',                      'field_name' => 'Total_HT',                    'field_type' => 'number',   'column_value' => null],
            ['document_id' => 48, 'field_title' => 'Total T.T.C',                    'field_name' => 'Total_T_T_C',                 'field_type' => 'number',   'column_value' => null],
            ['document_id' => 48, 'field_title' => 'Total TVA',                      'field_name' => 'Total_TVA',                   'field_type' => 'number',   'column_value' => null],
            ['document_id' => 48, 'field_title' => 'Prime CEE',                      'field_name' => 'Prime_CEE',                   'field_type' => 'number',   'column_value' => null],
            ['document_id' => 48, 'field_title' => "Prime MaPrimeRénov'",            'field_name' => 'Prime_MaPrimeRénov',          'field_type' => 'number',   'column_value' => null],
            ['document_id' => 48, 'field_title' => "Reste à payer",                  'field_name' => 'Reste_à_payer',               'field_type' => 'number',   'column_value' => null],
            ['document_id' => 48, 'field_title' => "Liste des travaux 1",            'field_name' => 'Liste_des_travaux_1',         'field_type' => 'select',   'column_value' => 'Liste_des_travaux_1'],
            ['document_id' => 48, 'field_title' => 'Chaudière - Marque 1',           'field_name' => 'Marque1',                     'field_type' => 'select',   'column_value' => 'marque_dropdown'],
            ['document_id' => 48, 'field_title' => 'Référence 1',                    'field_name' => 'Référence1',                  'field_type' => 'text',     'column_value' => null],
            ['document_id' => 48, 'field_title' => 'Montant HT 1',                   'field_name' => 'Montant_HT1',                 'field_type' => 'text',     'column_value' => null],
            ['document_id' => 48, 'field_title' => 'Montant TTC 1',                  'field_name' => 'Montant_TTC1',                'field_type' => 'text',     'column_value' => null],
            ['document_id' => 48, 'field_title' => 'Prime CEE 1',                      'field_name' => 'Prime_CEE1',                   'field_type' => 'text',     'column_value' => null],
            ['document_id' => 48, 'field_title' => "Liste des travaux 2",            'field_name' => 'Liste_des_travaux_2',         'field_type' => 'select',   'column_value' => 'Liste_des_travaux_2'],
            ['document_id' => 48, 'field_title' => 'Chaudière - Marque 2',           'field_name' => 'Marque2',                     'field_type' => 'select',   'column_value' => 'marque_dropdown'],
            ['document_id' => 48, 'field_title' => 'Référence 2',                    'field_name' => 'Référence2',                  'field_type' => 'text',     'column_value' => null],
            ['document_id' => 48, 'field_title' => 'Montant HT 2',                   'field_name' => 'Montant_HT2',                 'field_type' => 'text',     'column_value' => null],
            ['document_id' => 48, 'field_title' => 'Montant TTC 2',                  'field_name' => 'Montant_TTC2',                'field_type' => 'text',     'column_value' => null],
            ['document_id' => 48, 'field_title' => 'Prime CEE 2',                      'field_name' => 'Prime_CEE2',                   'field_type' => 'text',     'column_value' => null],


            ['document_id' => 49, 'field_title' => 'RESTE A CHARGE CLIENT',          'field_name' => 'RESTE_A_CHARGE_CLIENT',       'field_type' => 'number',   'column_value' => null],
            ['document_id' => 49, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 49, 'field_title' => 'POSEUR',                         'field_name' => 'POSEUR',                      'field_type' => 'text',     'column_value' => 'installer_technique'],
            ['document_id' => 49, 'field_title' => 'DATE POSE',                      'field_name' => 'DATE_POSE',                   'field_type' => 'date',     'column_value' => 'date_intervention'],
            ['document_id' => 49, 'field_title' => 'MATERIEL',                       'field_name' => 'MATERIEL',                    'field_type' => 'text',     'column_value' => null],
            ['document_id' => 49, 'field_title' => 'DEMANDE DE FACTURE PAR MAIL',    'field_name' => 'DEMANDE_DE_FACTURE_PAR_MAIL', 'field_type' => 'text',     'column_value' => 'Email'],
            ['document_id' => 50, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 50, 'field_title' => 'POSEUR',                         'field_name' => 'POSEUR',                      'field_type' => 'text',     'column_value' => 'installer_technique'],
            ['document_id' => 50, 'field_title' => 'DATE POSE',                      'field_name' => 'DATE_POSE',                   'field_type' => 'date',     'column_value' => 'date_intervention'],
            ['document_id' => 50, 'field_title' => 'MATERIEL',                       'field_name' => 'MATERIEL',                    'field_type' => 'text',     'column_value' => null],
            ['document_id' => 50, 'field_title' => 'DEMANDE DE FACTURE PAR MAIL',    'field_name' => 'DEMANDE_DE_FACTURE_PAR_MAIL', 'field_type' => 'text',     'column_value' => 'Email'],
            ['document_id' => 51, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 51, 'field_title' => 'POSEUR',                         'field_name' => 'POSEUR',                      'field_type' => 'text',     'column_value' => 'installer_technique'],
            ['document_id' => 51, 'field_title' => 'DATE POSE',                      'field_name' => 'DATE_POSE',                   'field_type' => 'date',     'column_value' => 'date_intervention'],
            ['document_id' => 51, 'field_title' => 'MATERIEL',                       'field_name' => 'MATERIEL',                    'field_type' => 'text',     'column_value' => null],
            ['document_id' => 51, 'field_title' => 'DEMANDE DE FACTURE PAR MAIL',    'field_name' => 'DEMANDE_DE_FACTURE_PAR_MAIL', 'field_type' => 'text',     'column_value' => 'Email'],
            ['document_id' => 52, 'field_title' => 'NOM CLIENT',                     'field_name' => 'NOM_CLIENT',                  'field_type' => 'text',     'column_value' => 'full_name'],
            ['document_id' => 52, 'field_title' => 'MATERIEL UTILISE',               'field_name' => 'MATERIEL_UTILISE',            'field_type' => 'textarea', 'column_value' => null],
            ['document_id' => 52, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 52, 'field_title' => 'Le',                             'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'date_intervention'],
            ['document_id' => 53, 'field_title' => 'Nom',                            'field_name' => 'Nom',                         'field_type' => 'text',     'column_value' => 'Nom'],
            ['document_id' => 53, 'field_title' => 'Prénom',                         'field_name' => 'Prénom',                      'field_type' => 'text',     'column_value' => 'Prenom'],
            ['document_id' => 53, 'field_title' => 'Téléphone',                      'field_name' => 'Téléphone',                   'field_type' => 'text',     'column_value' => 'phone'],
            ['document_id' => 53, 'field_title' => 'Adresse Travaux',                'field_name' => 'Adresse_Travaux',             'field_type' => 'text',     'column_value' => 'Adresse'],
            ['document_id' => 53, 'field_title' => 'Code Postal',                    'field_name' => 'Code_Postal',                 'field_type' => 'text',     'column_value' => 'Code_Postal'],
            ['document_id' => 53, 'field_title' => 'Ville',                          'field_name' => 'Ville',                       'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 53, 'field_title' => 'Fait à',                         'field_name' => 'Fait_à',                      'field_type' => 'text',     'column_value' => 'Ville'],
            ['document_id' => 53, 'field_title' => 'Le',                             'field_name' => 'Le',                          'field_type' => 'date',     'column_value' => 'today'],
            // ['document_id' => 53, 'field_title' => 'Atteste',                        'field_name' => 'Atteste',                     'field_type' => 'select',   'column_value' => 'Atteste_static'],
            ['document_id' => 53, 'field_title' => 'Mode de chauffage',              'field_name' => 'Mode_de_chauffage',           'field_type' => 'select',   'column_value' => 'Mode_de_chauffage__static2'],
        ];
        DocumentField::truncate();
        foreach($document_fields as $field){
            DocumentField::create([
                'document_id'   => $field ['document_id'],
                'field_title'   => $field ['field_title'],
                'field_name'    => $field ['field_name'],
                'field_type'    => $field ['field_type'],
                'column_value'  => $field ['column_value'],
            ]);
        }
    }
}
