<?php

namespace Database\Seeders;

use App\Models\BackOffice\Offer;
use App\Models\BackOffice\OfferBannerService;
use App\Models\BackOffice\OfferFifthBlockInfo;
use App\Models\BackOffice\OfferSixthBlockInfo;
use App\Models\BackOffice\OfferThirdBlockInfo;
use Illuminate\Database\Seeder;

class OfferSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $third_block_info = [
            [
                'image' => 'icon-1.svg',
                'title' => 'Un confort thermique',
                'description' => 'La PAC Air/Eau maintient et garantit une température constante pendant toute la saison hivernale. Vous profitez ainsi d’une chaleur douce dans toutes les pièces de votre logement.',
            ],
            [
                'image' => 'icon-2.svg',
                'title' => 'Un système écologique',
                'description' => 'La pompe à chaleur Air/Eau se distingue des autres types de chauffage exploitant les énergies fossiles. Puisant son énergie dans l’air, elle est donc inodore lors de son fonctionnement contrairement aux chaudières au fioul ou au gaz.',
            ],
            [
                'image' => 'icon-3.svg',
                'title' => 'Une plus value immobilière',
                'description' => 'Le chauffage étant le plus gros poste de dépense énergétique dans un logement, la pompe à chaleur Air/Eau vous fait gagner en étiquette énergétique. S’équiper d’une PAC Air/Eau permet ainsi d’améliorer sa performance énergétique et de valoriser son habitat. Une habitation chauffée au fioul sera classée E, F ou G sur le DPE (Diagnostic de Performance Energétique). Équipée d’une PAC Air/Eau, celle-ci valorisera son DPE en moyenne d’une étiquette.',
            ],
            [
                'image' => 'icon-4.svg',
                'title' => 'Une installation simple et efficace',
                'description' => 'La PAC Air/Eau se compose d’une unité extérieure et d’une unité intérieure, positionnée dans une des pièces de la maison. Peu volumineuse, elle ne requiert que peu d’espace et vous permet ainsi de garder l’esthétisme de votre logement. En plus de présenter une performance de chauffe, la pompe à chaleur Air/Eau ne nécessite, à l’inverse du bois ou du fioul, pas d’espace de stockage pour le combustible. Facile d’installation et d’entretien, la PAC Air/Eau est la solution de chauffage idéale dans le cadre de travaux de rénovation énergétique.',
            ],
        ];
        $fifth_block_info = [
            [
                'image' => 'icon-5.svg',
                'title' => "MaPrimeRénov'",
                'description' => "Versée par l'ANAH (Agence Nationale de l'Habitat), cette prime dépend des revenus de votre foyer et s'adresse aux personnes souhaitant se tourner vers des équipements plus respectueux de l'environnement en matière de chauffage, d'isolation, de VMC ou de chauffe-eau. Pour profiter de cette prime, vous devrez faire appel à un artisan qui détient le label RGE. (Réservée aux logements de plus de 15 ans.)",
            ],
            [
                'image' => 'icon-6.svg',
                'title' => 'La prime CEE',
                'description' => "Également appelée prime énergie, l'objectif de cette prime est de réduire de moitié la consommation d'énergie des Français d'ici à 2050. Versée directement par les fournisseurs d'énergie, cette aide peut prendre la forme de chèques, de cartes cadeaux, de réductions ou encore de services offerts. L'avantage : elle est accessible à tous les propriétaires sans condition de revenus.",
            ],
            [
                'image' => 'icon-7.svg',
                'title' => 'La TVA réduite à 5,5%',
                'description' => "Contrairement aux autres aides financières, celle-ci n'est pas constituée d'une prime que l'État verse aux propriétaires mais plutôt d'une réduction que les artisans et entreprises appliquent directement à leur facture, lorsque celle-ci est relative à des travaux de rénovation énergétique. Pour profiter de cette prime, vous devrez faire appel à un artisan qui détient le label RGE. (Réservée aux logements de plus de 15 ans.)",
            ],
            [
                'image' => 'icon-8.svg',
                'title' => 'Le crédit à taux zéro "Éco-PTZ"',
                'description' => "Ce crédit bancaire permet à tous les propriétaires qui souhaitent se lancer dans un projet de rénovation de leur maison de plus de deux ans sans condition de revenus. Pouvant aller jusqu'à 30 000 €, ce crédit sans intérêts couvre les travaux de remplacement de fenêtres, d'isolation, de remplacement de système de chauffage ou de production d'eau chaude et d'installation de VMC. Pour profiter de ce crédit à taux zéro, vous devrez faire appel à un artisan qui détient le label RGE.",
            ],
        ];
        $sixth_block_info = [
            [
                'image' => 'icon-1.png',
                'title' => 'Bénéficiez des primes de l’Etat pour financer vos travaux à moindre coû',
                'description' => 'Les solutions sont à partir de 1€.',
            ],
            [
                'image' => 'icon-2.png',
                'title' => 'Améliorez le confort de votre habitation',
                'description' => 'Été comme en hiver, cela permet d’améliorer grandement votre confort',
            ],
            [
                'image' => 'icon-3.png',
                'title' => 'Assurez la réalisation de votre chantier par un artisan « reconnu garant de l’environnement »',
                'description' => 'Gage de confiance, notre entreprise est « reconnu garant de l’environnement » (qualibat – RGE) et exerce dans le respect des normes et de l’excellence technique.',
            ],
            [
                'image' => 'icon-4.png',
                'title' => 'Réduisez considérablement vos factures en chauffage',
                'description' => 'Gage de confiance, notre entreprise est « reconnu garant de l’environnement » (qualibat – RGE) et exerce dans le respect des normes et de l’excellence technique.',
            ],
        ];
        $items = [
            [ 
                'category_id' => '1',
                'icon' => 'service-image-icon-1.svg',
                'feature_image' => 'feature_image-1.jpg',
                'banner_image' => 'banner-1.webp',
                'title' => 'Chaudière à Granulés',
                'subtitle' => "Jusqu'à 1 000€ d'économies par an",
                'home_page_button_text' => 'J’installe une PAC',
                'short_description' => 'Chaleur douce et homogène, Energie renouvelable',
                'long_description' => 'Mode de chauffage préféré des Français, la pompe à chaleur Chaudière à granulés (PAC) est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.',
                'banner_button_text' => "Estimez vos économies d'énergie",
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Modèle de référence : gamme Loki de HS France', 'Votre estimation gratuite en 2 minutes'],
            ],
            [ 
                'category_id' => '1',
                'icon' => 'service-image-icon-2.svg',
                'feature_image' => 'feature_image-2.jpg',
                'banner_image' => 'feature_image-2.jpg',
                'title' => 'Pompe à chaleur Air/Eau',
                'subtitle' => "Jusqu'à 1 000€ d'économies par an",
                'home_page_button_text' => "J’installe une PAC",
                'short_description' => 'Chaleur douce et homogène, Energie renouvelable',
                'long_description' => 'Mode de chauffage préféré des Français, la pompe à chaleur Air/Eau (PAC) est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.',
                'banner_button_text' => "Estimez vos économies d'énergie",
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['60% d’économies sur votre chauffage', 'Sélection de marques de référence sur le marché', 'Votre estimation gratuite en 2 minutes'],
            ],
            [ 
                'category_id' => '1',
                'icon' => 'service-image-icon-2.svg',
                'feature_image' => 'feature_image-3.jpg',
                'banner_image' => 'feature_image-3.jpg',
                'title' => 'Pompe à chaleur Air/Air',
                'subtitle' => "Jusqu'à 1 000€ d'économies par an",
                'home_page_button_text' => "J’installe une PAC",
                'short_description' => 'Chaleur douce et homogène, Energie renouvelable',
                'long_description' => 'Mode de chauffage préféré des Français, la pompe à chaleur Air/Air est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.',
                'banner_button_text' => "Estimez vos économies d'énergie",
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Jusqu’à 60% d’économies sur votre chauffage', 'Sélection de marques de référence sur le marché', 'Votre estimation gratuite en 2 minutes'],
            ],
            [ 
                'category_id' => '1',
                'icon' => 'service-image-icon-3.svg',
                'feature_image' => 'feature_image-4.jpg',
                'banner_image' => 'feature_image-4.jpg',
                'title' => 'Chauffe-eau thermodynamique',
                'subtitle' => "Des factures divisées par trois",
                'home_page_button_text' => "J’installe un chauffe-eau",
                'short_description' => 'Réactivité sur l’eau chaude, Energie renouvelable',
                'long_description' => 'Mode de chauffage préféré des Français, la pompe à chaleur Air/Air est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.',
                'banner_button_text' => "Estimez vos économies d'énergie",
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Divisez par 3 votre facture d’eau chaude sanitaire', 'Marques françaises de référence : Thaleos, Thermor', 'Votre estimation gratuite en 2 minutes'],
            ],
            [ 
                'category_id' => '1',
                'icon' => 'service-image-icon-1.svg',
                'feature_image' => 'feature_image-5.jpg',
                'banner_image' => 'feature_image-5.jpg',
                'title' => 'Chauffage d’appoint',
                'subtitle' => 'Jusqu’à 3 800€ d’aides',
                'home_page_button_text' => 'Je choisis mon chauffage',
                'short_description' => 'Gagnez en confort en installant un poêle à bûches, à granulés ou un insert cheminée.',
                'long_description' => 'Mode de chauffage préféré des Français, la pompe à chaleur Air/Air est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.',
                'banner_button_text' => "Estimez vos économies d'énergie",
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Divisez par 3 votre facture d’eau chaude sanitaire', 'Marques françaises de référence : Thaleos, Thermor', 'Votre estimation gratuite en 2 minutes'],
            ], 
            [ 
                'category_id' => '2',
                'icon' => 'service-image-icon-4.svg',
                'feature_image' => 'feature_image-6.jpg',
                'banner_image' => 'feature_image-6.jpg',
                'title' => 'Isolation des murs',
                'subtitle' => "Jusqu'à 25% d'économies d'énergie",
                'home_page_button_text' => "J’isole mes murs",
                'short_description' => 'Votre maison est plus belle et gagne en valeur.',
                'long_description' => "Mode de chauffage préféré des Français, la Isolation Thermique par l'Extérieur (ITE) est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.",
                'banner_button_text' => "Estimez vos économies d'énergie",
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Jusqu’à 60% d’économies sur votre chauffage', 'Marque française de référence : Weber Saint Gobain', 'Votre estimation gratuite en 2 minutes'],
            ],
            [ 
                'category_id' => '3',
                'icon' => 'service-image-icon-5.svg',
                'feature_image' => 'feature_image-7.jpg',
                'banner_image' => 'feature_image-7.jpg',
                'title' => 'Panneaux photovoltaïques',
                'subtitle' => "Jusqu'à 1 400€ d'économies par an",
                'home_page_button_text' => 'Je passe au solaire',
                'short_description' => "En installant des panneaux photovoltaïques sur votre toiture, vous : 1) Economisez 40% sur votre facture et valorisez votre maison, 2) Produisez votre propre énergie avec une ressource durable. Pensez au solaire hybride ! Une offre 2 en 1 pour produire votre électricité et votre eau chaude et économiser jusqu'à 80% sur votre facture.",
                'long_description' => "Mode de chauffage préféré des Français, la Isolation Thermique par l'Extérieur (ITE) est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.",
                'banner_button_text' => 'Estimez votre production solaire',
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Jusqu’à 50% d’économies sur votre facture d’électricité', 'Sélection de marques de référence sur le marché', 'Votre estimation gratuite en 1 minute'],
            ],
            [ 
                'category_id' => '3',
                'icon' => 'service-image-icon-2.svg',
                'feature_image' => 'feature_image-9.jpg',
                'banner_image' => 'banner-8.webp',
                'title' => 'Système Solaire Combiné (SSC)',
                'subtitle' => "Jusqu'à 1 400€ d'économies par an",
                'home_page_button_text' => "J’installe une PAC",
                'short_description' => 'Chaleur douce et homogène, Energie renouvelable',
                'long_description' => "Mode de chauffage préféré des Français, la Isolation Thermique par l'Extérieur (ITE) est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.",
                'banner_button_text' => "Estimez vos économies d'énergie",
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Divisez par 3 votre facture d’eau chaude sanitaire', 'Marques françaises de référence : Thaleos, Thermor', 'Votre estimation gratuite en 2 minutes'],
            ],
            [ 
                'category_id' => '3',
                'icon' => 'service-image-icon-2.svg',
                'feature_image' => 'feature_image-8.jpg',
                'banner_image' => 'feature_image-8.jpg',
                'title' => 'Chauffe Eau Solaire',
                'subtitle' => "Jusqu'à 1 400€ d'économies par an",
                'home_page_button_text' => "J’installe une PAC",
                'short_description' => 'Chaleur douce et homogène, Energie renouvelable',
                'long_description' => "Mode de chauffage préféré des Français, la Isolation Thermique par l'Extérieur (ITE) est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.",
                'banner_button_text' => "Estimez vos économies d'énergie",
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Divisez par 3 votre facture d’eau chaude sanitaire', 'Marques françaises de référence : Thaleos, Thermor', 'Votre estimation gratuite en 2 minutes'],
            ],
            [ 
                'category_id' => '3',
                'icon' => 'service-image-icon-2.svg',
                'feature_image' => 'feature_image-10.jpg',
                'banner_image' => 'banner-10.webp',
                'title' => 'Panneaux solaires « NOMADE »',
                'subtitle' => "Jusqu'à 1 400€ d'économies par an",
                'home_page_button_text' => 'J’installe une PAC',
                'short_description' => 'Chaleur douce et homogène, Energie renouvelable',
                'long_description' => "Mode de chauffage préféré des Français, la Isolation Thermique par l'Extérieur (ITE) est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.",
                'banner_button_text' => 'Estimez votre production solaire',
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Jusqu’à 70% d’économies sur votre facture d’électricité', 'Sélection de marques de référence sur le marché', 'Votre estimation gratuite en 1 minute'],
            ],
            [ 
                'category_id' => '4',
                'icon' => 'service-image-icon-3.svg',
                'feature_image' => 'feature_image-11.jpg',
                'banner_image' => 'banner-7.jpg',
                'title' => 'Rénovation Globale',
                'subtitle' => "Jusqu'à 25% d'économies d'énergie",
                'home_page_button_text' => 'J’isole mes murs',
                'short_description' => 'Votre maison est plus belle et gagne en valeur.',
                'long_description' => "Mode de chauffage préféré des Français, la Isolation Thermique par l'Extérieur (ITE) est une solution de chauffage écologique et économique. Basée sur l’utilisation d’une énergie renouvelable, la pompe à chaleur Air/Eau récupère les calories naturellement présentes dans l’air extérieur pour les restituer sous forme de chaleur au circuit de chauffage central.",
                'banner_button_text' => 'Estimez votre production solaire',
                'banner_button_link' => '',
                'first_block_status' => 'yes',
                'first_block_title' => 'En quoi la pompe à chaleur Air/Eau est-elle économique ?',
                'first_block_image' => 'services-details-section-1.webp',
                'first_block_desciption' => 'En fonctionnant avec l’air, la pompe à chaleur Air/Eau est un système de chauffage écologique et bien sûr économique. L’air étant une source inépuisable et gratuite, vous réduisez considérablement votre facture énergétique. Avec la pompe à chaleur Air/Eau, vous produisez davantage que vous ne consommez d’énergie. Par exemple, pour 1kWh d’électricité consommée, la PAC Air/Eau restitue 3 à 4 kWh de chaleur.

                Vous pouvez ainsi diviser par 3 à 4 le montant de votre facture.En plus de chauffer votre maison, la PAC Air/Eau produit de l’eau chaude sanitaire. En la couplant à un ballon ou à un chauffe-eau thermodynamique, vous économisez également sur vos frais d’eau chaude. Afin d’obtenir de réelles économies, il est important de bien dimensionner la PAC air/eau. En effet, un surdimensionnement entraine une surconsommation de l’équipement et une durée de vie plus courte. Pour maximiser les économies, il est conseillé de renforcer l’isolation de votre logement afin d’éviter les déperditions énergétiques et par conséquent réduire vos besoins en chauffage',
                'first_block_button_text' => 'Estimez le montant de vos aides',
                'first_block_button_link' => '#!',
                'second_block_status' => 'yes',
                'second_block_title' => 'Pompe à chaleur Air/Eau : quel est son principe ?',
                'second_block_image' => 'services-details-section-2.webp',
                'second_block_desciption' => 'Comme la Pac Air/Air, la PAC Air/Eau repose sur le système aérothermique c’est-à-dire qu’elle puise les calories contenues dans l’air extérieur pour les restituer sous forme de chaleur. Dans le cas de la PAC Air/Eau, c’est l’eau alimentant le chauffage qui est utilisée pour augmenter la température du logement. La pompe à chaleur Air/Eau se compose d’une unité extérieure, qui puise les calories de l’air, et d’une unité intérieure qui redistribue l’énergie dans le circuit de chauffage. Le fluide frigorigène, contenu dans la PAC Air/Eau permet cette transformation. Capable de transporter la chaleur, le fluide frigorigène passe sous différentes formes (liquide et gazeux) pour émettre la chaleur au sein du logement.',
                'second_block_button_text' => 'Estimez le montant de vos aides',
                'second_block_button_link' => '#!',
                'third_block_status' => 'yes',
                'third_block_title' => 'Quels sont les avantagesde la PAC Air/Eau ?',
                'fourth_block_status' => 'yes',
                'fourth_block_title' => 'Quel est le prix d’une pompe à chaleur Air/Eau ?',
                'fourth_block_image' => 'services-details-section-3.webp',
                'fourth_block_desciption' => 'La pompe à chaleur Air/Eau est l’un des systèmes écologiques les plus courants dans les foyers français. Avec un prix moyen situé autour de 12 000 € (installation comprise) et le soutien de l’Etat, le reste à charge d’une pompe à chaleur air eau devient accessible au plus grand nombre. Chez TUCOENERGIE, nous avons sélectionné pour vous les meilleurs PAC Air/Eau du marché des marque Atlantic, Daikin et Hitachi. Nous désignons un artisan qualifié RGE qui interviendra au plus vite pour l’installation de votre PAC Air/Eau. De l’étude de faisabilité à la mise en service, en passant par la prise en charge des démarches administratives TUCOENERGIE vous propose un projet clé en main.',
                'fourth_block_button_text' => 'Estimez le montant de vos aides',
                'fourth_block_button_link' => '#!',
                'fifth_block_status' => 'yes',
                'fifth_block_title' => 'À quelles aides financières ai-je le droit',
                'fifth_block_description' => "Depuis quelques années, le Gouvernement français encourage les propriétaires de maisons, d'immeubles et de locaux en général à procéder à des travaux destinés à les rendre moins énergivores et donc à réduire les émissions de CO2 et l'utilisation d'énergies fossiles. Pour cela, un certain nombre de primes, d'aides financières et de crédits d'impôts peuvent vous être alloués si vous correspondez aux critères demandés. Si vous souhaitez installer un chauffe-eau thermodynamique dans votre logement, vous pouvez par exemple bénéficier de :",
                'sixth_block_status' => 'yes',
                'sixth_block_title' => "4 bonnes raisons d'éco-rénover votre logement maintenant !",
                'banner_service' => ['Jusqu’à 70% d’économies sur votre facture d’électricité', 'Sélection de marques de référence sur le marché', 'Votre estimation gratuite en 1 minute'],
            ],
        ];

        Offer::truncate();
        OfferBannerService::truncate();
        OfferThirdBlockInfo::truncate();
        OfferFifthBlockInfo::truncate();
        OfferSixthBlockInfo::truncate();

        foreach ($items as $item){
            $offer = Offer::create([
                'category_id' => $item['category_id'], 
                'icon' => $item['icon'], 
                'feature_image' => $item['feature_image'], 
                'banner_image' => $item['banner_image'], 
                'title' => $item['title'], 
                'subtitle' => $item['subtitle'], 
                'home_page_button_text' => $item['home_page_button_text'], 
                'short_description' => $item['short_description'], 
                'long_description' => $item['long_description'], 
                'banner_button_text' => $item['banner_button_text'], 
                'banner_button_link' => $item['banner_button_link'], 
                'first_block_status' => $item['first_block_status'], 
                'first_block_title' => $item['first_block_title'], 
                'first_block_image' => $item['first_block_image'], 
                'first_block_desciption' => $item['first_block_desciption'], 
                'first_block_button_text' => $item['first_block_button_text'], 
                'first_block_button_link' => $item['first_block_button_link'], 
                'second_block_status' => $item['second_block_status'], 
                'second_block_title' => $item['second_block_title'], 
                'second_block_image' => $item['second_block_image'], 
                'second_block_desciption' => $item['second_block_desciption'], 
                'second_block_button_text' => $item['second_block_button_text'], 
                'second_block_button_link' => $item['second_block_button_link'], 
                'third_block_status' => $item['third_block_status'], 
                'third_block_title' => $item['third_block_title'], 
                'fourth_block_status' => $item['fourth_block_status'], 
                'fourth_block_title' => $item['fourth_block_title'], 
                'fourth_block_image' => $item['fourth_block_image'], 
                'fourth_block_desciption' => $item['fourth_block_desciption'], 
                'fourth_block_button_text' => $item['fourth_block_button_text'], 
                'fourth_block_button_link' => $item['fourth_block_button_link'], 
                'fifth_block_status' => $item['fifth_block_status'], 
                'fifth_block_title' => $item['fifth_block_title'], 
                'fifth_block_description' => $item['fifth_block_description'], 
                'sixth_block_status' => $item['sixth_block_status'], 
                'sixth_block_title' => $item['sixth_block_title'],
            ]);
            foreach($item['banner_service'] as $service){
                OfferBannerService::create([
                    'offer_id' => $offer->id,
                    'name' => $service,
                ]);
            }
            foreach($third_block_info as $third_block){
                OfferThirdBlockInfo::create([
                    'offer_id' => $offer->id,
                    'image' => $third_block['image'],
                    'title' => $third_block['title'],
                    'description' => $third_block['description'],
                ]);
            }
            foreach($fifth_block_info as $fifth_block){
                OfferFifthBlockInfo::create([
                    'offer_id' => $offer->id,
                    'image' => $fifth_block['image'],
                    'title' => $fifth_block['title'],
                    'description' => $fifth_block['description'],
                ]);
            }
            foreach($sixth_block_info as $sixth_block){
                OfferSixthBlockInfo::create([
                    'offer_id' => $offer->id,
                    'image' => $sixth_block['image'],
                    'title' => $sixth_block['title'],
                    'description' => $sixth_block['description'],
                ]);
            }

        }
    }
}
