<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateQualityControlsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('quality_controls', function (Blueprint $table) {
            $table->id();
            $table->integer('project_id')->nullable(); 
            $table->text('quality_control_type')->nullable(); 
            $table->text('etude_quality_control_date')->nullable(); 
            $table->text('etude_operator')->nullable(); 
            $table->text('etude_client_name')->nullable(); 
            $table->text('etude_postal_code')->nullable(); 
            $table->text('etude_sales_meeting_date')->nullable(); 
            $table->text('etude_project')->nullable(); 
            $table->text('etude_commercial')->nullable(); 
            $table->text('etude_introduction_operator')->nullable(); 
            $table->text('etude_project_details')->nullable(); 
            $table->text('etude_meeting_experience')->nullable(); 
            $table->text('etude_evaluation_rating')->nullable(); 
            $table->text('etude_remind_me')->nullable(); 
            $table->text('etude_occupants_number')->nullable(); 
            $table->text('etude_home_built_time')->nullable(); 
            $table->text('etude_surface')->nullable(); 
            $table->text('etude_heating_type')->nullable(); 
            $table->text('etude_heated_levels')->nullable(); 
            $table->text('etude_transmitters_type')->nullable(); 
            $table->text('etude_other_transmitters_type')->nullable(); 
            $table->text('etude_hot_water_production')->nullable(); 
            $table->text('etude_other_hot_water_production')->nullable(); 
            $table->text('etude_have_insulation')->nullable(); 
            $table->text('etude_have_insulation_wall')->nullable(); 
            $table->text('etude_have_insulation_basement')->nullable(); 
            $table->text('etude_boiler_model')->nullable(); 
            $table->text('etude_esc_model')->nullable(); 
            $table->text('etude_bio_services')->nullable(); 
            $table->text('etude_question_material')->nullable(); 
            $table->text('etude_professional_situation')->nullable(); 
            $table->text('etude_other_professional_situation')->nullable(); 
            $table->text('etude_family_situation')->nullable(); 
            $table->text('etude_have_children')->nullable(); 
            $table->text('etude_monthly_income')->nullable(); 
            $table->text('etude_current_credits')->nullable(); 
            $table->text('etude_credit_1')->nullable(); 
            $table->text('etude_credit_2')->nullable(); 
            $table->text('etude_credit_3')->nullable(); 
            $table->text('etude_credit_4')->nullable(); 
            $table->text('etude_bank_status')->nullable(); 
            $table->text('etude_have_bdc_copy')->nullable(); 
            $table->text('etude_approved_funding')->nullable(); 
            $table->text('etude_monthly_payments')->nullable(); 
            $table->text('etude_financing_partner')->nullable(); 
            $table->text('etude_eec_amount')->nullable(); 
            $table->text('etude_renov_amount')->nullable(); 
            $table->text('etude_renov_paid')->nullable(); 
            $table->text('etude_deferral_system')->nullable(); 
            $table->text('etude_know_more')->nullable(); 
            $table->text('etude_motivational_note')->nullable(); 
            $table->text('etude_general_comments')->nullable(); 
            $table->text('installation_quality_control_date')->nullable(); 
            $table->text('installation_operator')->nullable(); 
            $table->text('installation_client_name')->nullable(); 
            $table->text('installation_postal_code')->nullable(); 
            $table->text('installation_installed_date')->nullable(); 
            $table->text('installation_project')->nullable(); 
            $table->text('installation_installer')->nullable(); 
            $table->text('installation_other_installer')->nullable(); 
            $table->text('installation_commercial')->nullable(); 
            $table->text('installation_other_commercial')->nullable(); 
            $table->text('installation_satisfied')->nullable(); 
            $table->text('installation_equipment_installed')->nullable(); 
            $table->text('installation_evaluation')->nullable(); 
            $table->text('installation_score')->nullable(); 
            $table->text('installation_recommend')->nullable(); 
            $table->text('installation_mpr_contact')->nullable(); 
            $table->text('installation_identity_validation')->nullable(); 
            $table->text('installation_file_validation')->nullable(); 
            $table->text('installation_address_validation')->nullable(); 
            $table->text('installation_company_validation')->nullable(); 
            $table->text('installation_work_validation')->nullable(); 
            $table->text('installation_proxy_validation')->nullable(); 
            $table->text('installation_validation_comment')->nullable(); 
            $table->text('installation_amount_validation')->nullable(); 
            $table->text('installation_expense_validation')->nullable(); 
            $table->text('installation_client_respond')->nullable(); 
            $table->text('installation_paid_consent')->nullable(); 
            $table->text('installation_customer_call')->nullable(); 
            $table->text('installation_receive_invoice')->nullable(); 
            $table->text('installation_review')->nullable(); 
            $table->text('installation_carry_out')->nullable(); 
            $table->text('installation_action_logement')->nullable(); 
            $table->text('installation_contact_us')->nullable(); 
            $table->text('installation_contact_soon')->nullable(); 
            $table->text('installation_release_fund')->nullable(); 
            $table->text('installation_observations')->nullable(); 
            $table->text('previsite_quality_control_date')->nullable(); 
            $table->text('previsite_operator')->nullable(); 
            $table->text('previsite_client_name')->nullable(); 
            $table->text('previsite_postal_code')->nullable(); 
            $table->text('previsite_sales_meeting_date')->nullable(); 
            $table->text('previsite_project')->nullable(); 
            $table->text('previsite_commercial')->nullable(); 
            $table->text('previsite_introduction_operator')->nullable(); 
            $table->text('previsite_project_details')->nullable(); 
            $table->text('previsite_meeting_experience')->nullable(); 
            $table->text('previsite_evaluation_rating')->nullable(); 
            $table->text('previsite_remind_me')->nullable(); 
            $table->text('previsite_occupants_number')->nullable(); 
            $table->text('previsite_home_built_time')->nullable(); 
            $table->text('previsite_surface')->nullable(); 
            $table->text('previsite_heating_type')->nullable(); 
            $table->text('previsite_heated_levels')->nullable(); 
            $table->text('previsite_transmitters_type')->nullable(); 
            $table->text('previsite_other_transmitters_type')->nullable(); 
            $table->text('previsite_hot_water_production')->nullable(); 
            $table->text('previsite_other_hot_water_production')->nullable(); 
            $table->text('previsite_have_insulation')->nullable(); 
            $table->text('previsite_have_insulation_option')->nullable(); 
            $table->text('previsite_have_insulation_wall')->nullable(); 
            $table->text('previsite_have_insulation_wall_option')->nullable(); 
            $table->text('previsite_have_insulation_basement')->nullable(); 
            $table->text('previsite_have_insulation_basement_option')->nullable(); 
            $table->text('previsite_boiler_model')->nullable(); 
            $table->text('previsite_esc_model')->nullable(); 
            $table->text('previsite_bio_services')->nullable(); 
            $table->text('previsite_question_material')->nullable(); 
            $table->text('previsite_question_material_other')->nullable(); 
            $table->text('previsite_professional_situation')->nullable(); 
            $table->text('previsite_other_professional_situation')->nullable(); 
            $table->text('previsite_family_situation')->nullable(); 
            $table->text('previsite_have_children')->nullable(); 
            $table->text('previsite_children_name')->nullable(); 
            $table->text('previsite_children_birth_date')->nullable(); 
            $table->text('previsite_monthly_income')->nullable(); 
            $table->text('previsite_current_credits')->nullable(); 
            $table->text('previsite_credit_1')->nullable(); 
            $table->text('previsite_credit_2')->nullable(); 
            $table->text('previsite_credit_3')->nullable(); 
            $table->text('previsite_credit_4')->nullable(); 
            $table->text('previsite_bank_status')->nullable(); 
            $table->text('previsite_have_bdc_copy')->nullable(); 
            $table->text('previsite_approved_funding')->nullable(); 
            $table->text('previsite_monthly_payments')->nullable(); 
            $table->text('previsite_financing_partner')->nullable(); 
            $table->text('previsite_eec_amount')->nullable(); 
            $table->text('previsite_renov_amount')->nullable(); 
            $table->text('previsite_renov_paid')->nullable(); 
            $table->text('previsite_deferral_system')->nullable(); 
            $table->text('previsite_know_more')->nullable(); 
            $table->text('previsite_motivational_note')->nullable(); 
            $table->text('previsite_general_comments')->nullable(); 
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('quality_controls');
    }
}
